### ISSUE TITLE
Sample Issue

### ISSUE THREAD

**Issue by azooz2003-bit** [gtiosclub/CanvasPlusPlayground#104]
#### Sub-Issues:
- [ ] [#123] Implement API endpoint
- [ ] [#124] Design the UI component
- [ ] [#125] Write unit tests for Feature X
